#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa
        AAAAB3NzaC1yc2EAAAADAQABAAABAQCPIIO8uY8oWIihDv0tCAbX6toyG1RYkaLZyfGD1L+I07K4CnwAVBSU+81vw3Yv5sN9tj2Ccve9kzEeCNMld2mDP/Tt7edkx2MCToVfVx+njqwY/XbMY9bfdRKJLhIoLavuVNLnnkSIXdtlGr3JF71hPHzBDMEo64ofPCQ8hPsGxL1u3efb12jcWcRhudKtv7Qh6cVE47Zj4xImfi6VlLqwzcKZ5oCqR/z1hLLL+/pS3eM5Qsor5wmAqNfH4+z5eE+pOkFm7a0Nkygv9jwXIqtJzFGKYDe6ciBD04pEovdvY0FTyiv2vksQOVgjtu2faG2Iv1HOG0JktCIwJ49OEgjT
        teacher-key
      - ssh-rsa
        AAAAB3NzaC1yc2EAAAADAQABAAABAQCqCagxMF1aixN00RMl7PqpPUMyWGSZyHVDTuuN6r5WOxNa2LctWYkN/40QrU4N+4KZufbeW3w657x0+yCxXgkbOFJX/J70XQy9M6EhJCo1tstP8FgI1n0om1ZnG7pQqEV/MSZmMD6XL6lxOKUVvNzWQwkjIIKIrEdPXZiZHcC2yBfbUH3yAZhDlRp2oO62GfeIk3NV5KaaGjQVoPDBCAGUdXnw+RLHlFhPmNC0KCYHEUd78LeUnQIWzjdZZBbN+9EQTZ/MZVSa7RGN+DLJm+ZfKjnfUOBRbC1xtoRpnHOs8PYmp5F8tdiJ36+KGpZF22DRXMC3RXmkR9lEFyd3AWhH
ssh_pwauth: false
disable_root: false
package_update: true
packages:
  - unzip
  - gnupg
  - curl
write_files:
  - path: /home/ubuntu/mongodconfupdate.sh
    content: >
      sudo sed -i 's/#security:/security:\n  authorization: enabled/g'
      /etc/mongod.conf
  - path: /home/ubuntu/mongodbuser.txt
    content: |
      use admin;
      db.createUser(
        {
          user: "admin",
          pwd: "12345",
          roles: [
            { role: "userAdminAnyDatabase", db: "admin" },
            { role: "readWriteAnyDatabase", db: "admin" }
          ]
        }
      );
runcmd:
  - curl -fsSL https://pgp.mongodb.com/server-6.0.asc | sudo gpg -o
    /usr/share/keyrings/mongodb-server-6.0.gpg --dearmor
  - echo "deb [ arch=amd64,arm64
    signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ]
    https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo
    tee /etc/apt/sources.list.d/mongodb-org-6.0.list
  - sudo apt-get update -y
  - sudo apt-get install -y mongodb-org
  - sudo sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mongod.conf
  - sudo chmod +x /home/ubuntu/mongodconfupdate.sh
  - sudo /home/ubuntu/mongodconfupdate.sh
  - sudo systemctl enable mongod
  - sudo systemctl start mongod
  - sudo sleep 3
  - sudo mongosh < /home/ubuntu/mongodbuser.txt
  - sudo systemctl restart mongod
